apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-operation
  namespace: plarail2023
spec:
  selector:
    matchLabels:
      app: auto-operation
  template:
    metadata:
      labels:
        app: auto-operation
    spec:
      containers:
        - name: auto-operation
          image: ghcr.io/ueckoken/plarail2023-autooperation:deployment-d17e785-1700807874  # {"$imagepolicy": "plarail2021:auto-operation"}
          imagePullPolicy: Always
          env:
            - name: SERVER_ADDR
              value: 'http://state-manager:8080'
            