//
//Point Proto
//ポイントレールの状態を扱うプロトコル

// @generated by protoc-gen-es v1.4.2 with parameter "target=dts+js"
// @generated from file state/v1/point.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum state.v1.PointStateEnum
 */
export const PointStateEnum = proto3.makeEnum(
  "state.v1.PointStateEnum",
  [
    {no: 0, name: "POINT_STATE_UNKNOWN"},
    {no: 1, name: "POINT_STATE_NORMAL"},
    {no: 2, name: "POINT_STATE_REVERSE"},
  ],
);

/**
 * @generated from message state.v1.PointAndState
 */
export const PointAndState = proto3.makeMessageType(
  "state.v1.PointAndState",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "enum", T: proto3.getEnumType(PointStateEnum) },
  ],
);

/**
 *
 * UpdatePointState : ポイントの状態を更新するAPI
 *
 * @generated from message state.v1.UpdatePointStateRequest
 */
export const UpdatePointStateRequest = proto3.makeMessageType(
  "state.v1.UpdatePointStateRequest",
  () => [
    { no: 1, name: "state", kind: "message", T: PointAndState },
  ],
);

/**
 * @generated from message state.v1.UpdatePointStateResponse
 */
export const UpdatePointStateResponse = proto3.makeMessageType(
  "state.v1.UpdatePointStateResponse",
  [],
);

/**
 *
 * GetPointStates : 全てのポイントの状態を取得するAPI
 *
 * @generated from message state.v1.GetPointStatesRequest
 */
export const GetPointStatesRequest = proto3.makeMessageType(
  "state.v1.GetPointStatesRequest",
  [],
);

/**
 * @generated from message state.v1.GetPointStatesResponse
 */
export const GetPointStatesResponse = proto3.makeMessageType(
  "state.v1.GetPointStatesResponse",
  () => [
    { no: 1, name: "states", kind: "message", T: PointAndState, repeated: true },
  ],
);

