// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=dts+js"
// @generated from file state/v1/state.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlockStatesRequest, GetBlockStatesResponse, UpdateBlockStateRequest, UpdateBlockStateResponse } from "./block_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { GetPointStatesRequest, GetPointStatesResponse, UpdatePointStateRequest, UpdatePointStateResponse } from "./point_pb.js";
import { GetStopStatesRequest, GetStopStatesResponse, UpdateStopStateRequest, UpdateStopStateResponse } from "./stop_pb.js";
import { AddTrainRequest, AddTrainResponse, GetTrainsRequest, GetTrainsResponse, UpdateTrainRequest, UpdateTrainResponse } from "./train_pb.js";

/**
 *
 * StateManagerが提供するサービス
 * AutoOperationとフロントエンド間の通信に利用される
 *
 * @generated from service state.v1.StateManagerService
 */
export declare const StateManagerService: {
  readonly typeName: "state.v1.StateManagerService",
  readonly methods: {
    /**
     * Block 
     *
     * @generated from rpc state.v1.StateManagerService.GetBlockStates
     */
    readonly getBlockStates: {
      readonly name: "GetBlockStates",
      readonly I: typeof GetBlockStatesRequest,
      readonly O: typeof GetBlockStatesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateBlockState
     */
    readonly updateBlockState: {
      readonly name: "UpdateBlockState",
      readonly I: typeof UpdateBlockStateRequest,
      readonly O: typeof UpdateBlockStateResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Point 
     *
     * @generated from rpc state.v1.StateManagerService.UpdatePointState
     */
    readonly updatePointState: {
      readonly name: "UpdatePointState",
      readonly I: typeof UpdatePointStateRequest,
      readonly O: typeof UpdatePointStateResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetPointStates
     */
    readonly getPointStates: {
      readonly name: "GetPointStates",
      readonly I: typeof GetPointStatesRequest,
      readonly O: typeof GetPointStatesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Stop 
     *
     * @generated from rpc state.v1.StateManagerService.UpdateStopState
     */
    readonly updateStopState: {
      readonly name: "UpdateStopState",
      readonly I: typeof UpdateStopStateRequest,
      readonly O: typeof UpdateStopStateResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetStopStates
     */
    readonly getStopStates: {
      readonly name: "GetStopStates",
      readonly I: typeof GetStopStatesRequest,
      readonly O: typeof GetStopStatesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Train 
     *
     * @generated from rpc state.v1.StateManagerService.GetTrains
     */
    readonly getTrains: {
      readonly name: "GetTrains",
      readonly I: typeof GetTrainsRequest,
      readonly O: typeof GetTrainsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.AddTrain
     */
    readonly addTrain: {
      readonly name: "AddTrain",
      readonly I: typeof AddTrainRequest,
      readonly O: typeof AddTrainResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateTrain
     */
    readonly updateTrain: {
      readonly name: "UpdateTrain",
      readonly I: typeof UpdateTrainRequest,
      readonly O: typeof UpdateTrainResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

