[book]
authors = ["ぼいど","きえん"]
language = "ja"
multilingual = false
src = "src"
title = "ueckoken-plarail-documents"

[output.html]
git-repository-url = "https://github.com/ueckoken/plarail2023"
git-repository-icon = "fa-github"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
