apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tlscert
  namespace: cert-manager
spec:
  secretName: cloudflare-cert
  dnsNames:
    - "*.plarail.k1h.dev"
    - "plarail.k1h.dev"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io