apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: admin@k1h.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
#    solvers:
#      - dns01:
#          cloudflare:
#            email: admin@k1h.dev
#            apiKeySecretRef:
#              name: cloudflare-api-token-secret
#              key: api-token