apiVersion: v1
kind: Service
metadata:
  name: state-manager
  namespace: plarail2023
  labels:
    app: state-manager
spec:
  type: ClusterIP
  selector:
    app: state-manager
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
