version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
  state-manager:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/backend/state-manager/Dockerfile
    ports:
      - 8080:8080
    environment:
      - MQTT_BROKER_ADDR=tls://e57dee86.ala.asia-southeast1.emqxsl.com:8883
      - MQTT_USERNAME=test
      - MQTT_PASSWORD=password
      - MQTT_CLIENT_ID=emqx_cloudd1e033
      - MONGODB_URI=mongodb://root:password@mongo:27017/
      - APP_ENV=prod
    depends_on:
      - mongo
    healthcheck:
      test: curl --fail http://localhost:8080/debug/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
  auto-operation:
    build: 
      context: .
      dockerfile: ./docker/backend/auto-operation/Dockerfile
    environment:
      - SERVER_ADDR=http://state-manager:8080
    depends_on:
      state-manager:
        condition: service_healthy