apiVersion: v1
kind: Service
metadata:
  name: state-manager
  labels:
    app: state-manager
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: state-manager
