//
//Point Proto
//ポイントレールの状態を扱うプロトコル

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: state/v1/point.proto

package statev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointStateEnum int32

const (
	PointStateEnum_POINT_STATE_UNKNOWN PointStateEnum = 0
	PointStateEnum_POINT_STATE_NORMAL  PointStateEnum = 1 // ポイントがまっすぐな状態
	PointStateEnum_POINT_STATE_REVERSE PointStateEnum = 2 // ポイントが移動している状態
)

// Enum value maps for PointStateEnum.
var (
	PointStateEnum_name = map[int32]string{
		0: "POINT_STATE_UNKNOWN",
		1: "POINT_STATE_NORMAL",
		2: "POINT_STATE_REVERSE",
	}
	PointStateEnum_value = map[string]int32{
		"POINT_STATE_UNKNOWN": 0,
		"POINT_STATE_NORMAL":  1,
		"POINT_STATE_REVERSE": 2,
	}
)

func (x PointStateEnum) Enum() *PointStateEnum {
	p := new(PointStateEnum)
	*p = x
	return p
}

func (x PointStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_state_v1_point_proto_enumTypes[0].Descriptor()
}

func (PointStateEnum) Type() protoreflect.EnumType {
	return &file_state_v1_point_proto_enumTypes[0]
}

func (x PointStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointStateEnum.Descriptor instead.
func (PointStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{0}
}

type PointAndState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                     // ポイントのid
	State PointStateEnum `protobuf:"varint,2,opt,name=state,proto3,enum=state.v1.PointStateEnum" json:"state,omitempty"` // ポイントの状態
}

func (x *PointAndState) Reset() {
	*x = PointAndState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_point_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointAndState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointAndState) ProtoMessage() {}

func (x *PointAndState) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_point_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointAndState.ProtoReflect.Descriptor instead.
func (*PointAndState) Descriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{0}
}

func (x *PointAndState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PointAndState) GetState() PointStateEnum {
	if x != nil {
		return x.State
	}
	return PointStateEnum_POINT_STATE_UNKNOWN
}

// UpdatePointState : ポイントの状態を更新するAPI
type UpdatePointStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *PointAndState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UpdatePointStateRequest) Reset() {
	*x = UpdatePointStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_point_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePointStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointStateRequest) ProtoMessage() {}

func (x *UpdatePointStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_point_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointStateRequest.ProtoReflect.Descriptor instead.
func (*UpdatePointStateRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePointStateRequest) GetState() *PointAndState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdatePointStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePointStateResponse) Reset() {
	*x = UpdatePointStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_point_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePointStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointStateResponse) ProtoMessage() {}

func (x *UpdatePointStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_point_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointStateResponse.ProtoReflect.Descriptor instead.
func (*UpdatePointStateResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{2}
}

// GetPointStates : 全てのポイントの状態を取得するAPI
type GetPointStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPointStatesRequest) Reset() {
	*x = GetPointStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_point_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPointStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointStatesRequest) ProtoMessage() {}

func (x *GetPointStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_point_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointStatesRequest.ProtoReflect.Descriptor instead.
func (*GetPointStatesRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{3}
}

type GetPointStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*PointAndState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *GetPointStatesResponse) Reset() {
	*x = GetPointStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_point_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPointStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointStatesResponse) ProtoMessage() {}

func (x *GetPointStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_point_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointStatesResponse.ProtoReflect.Descriptor instead.
func (*GetPointStatesResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_point_proto_rawDescGZIP(), []int{4}
}

func (x *GetPointStatesResponse) GetStates() []*PointAndState {
	if x != nil {
		return x.States
	}
	return nil
}

var File_state_v1_point_proto protoreflect.FileDescriptor

var file_state_v1_point_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x4f, 0x0a, 0x0d, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x48, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x49, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2a, 0x5a, 0x0a, 0x0e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x17, 0x0a,
	0x13, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x56, 0x45, 0x52, 0x53, 0x45, 0x10, 0x02, 0x42, 0x9a, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x75, 0x65, 0x63, 0x6b, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x72,
	0x61, 0x69, 0x6c, 0x32, 0x30, 0x32, 0x33, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x73, 0x70, 0x65, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x14, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_state_v1_point_proto_rawDescOnce sync.Once
	file_state_v1_point_proto_rawDescData = file_state_v1_point_proto_rawDesc
)

func file_state_v1_point_proto_rawDescGZIP() []byte {
	file_state_v1_point_proto_rawDescOnce.Do(func() {
		file_state_v1_point_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_v1_point_proto_rawDescData)
	})
	return file_state_v1_point_proto_rawDescData
}

var file_state_v1_point_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_v1_point_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_state_v1_point_proto_goTypes = []interface{}{
	(PointStateEnum)(0),              // 0: state.v1.PointStateEnum
	(*PointAndState)(nil),            // 1: state.v1.PointAndState
	(*UpdatePointStateRequest)(nil),  // 2: state.v1.UpdatePointStateRequest
	(*UpdatePointStateResponse)(nil), // 3: state.v1.UpdatePointStateResponse
	(*GetPointStatesRequest)(nil),    // 4: state.v1.GetPointStatesRequest
	(*GetPointStatesResponse)(nil),   // 5: state.v1.GetPointStatesResponse
}
var file_state_v1_point_proto_depIdxs = []int32{
	0, // 0: state.v1.PointAndState.state:type_name -> state.v1.PointStateEnum
	1, // 1: state.v1.UpdatePointStateRequest.state:type_name -> state.v1.PointAndState
	1, // 2: state.v1.GetPointStatesResponse.states:type_name -> state.v1.PointAndState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_state_v1_point_proto_init() }
func file_state_v1_point_proto_init() {
	if File_state_v1_point_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_state_v1_point_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointAndState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_point_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePointStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_point_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePointStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_point_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPointStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_point_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPointStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_v1_point_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_v1_point_proto_goTypes,
		DependencyIndexes: file_state_v1_point_proto_depIdxs,
		EnumInfos:         file_state_v1_point_proto_enumTypes,
		MessageInfos:      file_state_v1_point_proto_msgTypes,
	}.Build()
	File_state_v1_point_proto = out.File
	file_state_v1_point_proto_rawDesc = nil
	file_state_v1_point_proto_goTypes = nil
	file_state_v1_point_proto_depIdxs = nil
}
