//
//Stop Proto
//ストップレールの状態を扱うプロトコル

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: state/v1/stop.proto

package statev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopStateEnum int32

const (
	StopStateEnum_STOP_STATE_UNKNOWN StopStateEnum = 0
	StopStateEnum_STOP_STATE_GO      StopStateEnum = 1 // バーが下がってる状態
	StopStateEnum_STOP_STATE_STOP    StopStateEnum = 2 // バーが上がってる状態
)

// Enum value maps for StopStateEnum.
var (
	StopStateEnum_name = map[int32]string{
		0: "STOP_STATE_UNKNOWN",
		1: "STOP_STATE_GO",
		2: "STOP_STATE_STOP",
	}
	StopStateEnum_value = map[string]int32{
		"STOP_STATE_UNKNOWN": 0,
		"STOP_STATE_GO":      1,
		"STOP_STATE_STOP":    2,
	}
)

func (x StopStateEnum) Enum() *StopStateEnum {
	p := new(StopStateEnum)
	*p = x
	return p
}

func (x StopStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_state_v1_stop_proto_enumTypes[0].Descriptor()
}

func (StopStateEnum) Type() protoreflect.EnumType {
	return &file_state_v1_stop_proto_enumTypes[0]
}

func (x StopStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopStateEnum.Descriptor instead.
func (StopStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{0}
}

type StopAndState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // ポイントのid
	State StopStateEnum `protobuf:"varint,2,opt,name=state,proto3,enum=state.v1.StopStateEnum" json:"state,omitempty"` // ポイントの状態
}

func (x *StopAndState) Reset() {
	*x = StopAndState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_stop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAndState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAndState) ProtoMessage() {}

func (x *StopAndState) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_stop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAndState.ProtoReflect.Descriptor instead.
func (*StopAndState) Descriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{0}
}

func (x *StopAndState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopAndState) GetState() StopStateEnum {
	if x != nil {
		return x.State
	}
	return StopStateEnum_STOP_STATE_UNKNOWN
}

// UpdateStopState : ストップレールの状態を更新するAPI
type UpdateStopStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *StopAndState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UpdateStopStateRequest) Reset() {
	*x = UpdateStopStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_stop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStopStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStopStateRequest) ProtoMessage() {}

func (x *UpdateStopStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_stop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStopStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateStopStateRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStopStateRequest) GetState() *StopAndState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateStopStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateStopStateResponse) Reset() {
	*x = UpdateStopStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_stop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStopStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStopStateResponse) ProtoMessage() {}

func (x *UpdateStopStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_stop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStopStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateStopStateResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{2}
}

// GetStopStates : 全てのストップレールの状態を取得するAPI
type GetStopStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStopStatesRequest) Reset() {
	*x = GetStopStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_stop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStopStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStopStatesRequest) ProtoMessage() {}

func (x *GetStopStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_stop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStopStatesRequest.ProtoReflect.Descriptor instead.
func (*GetStopStatesRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{3}
}

type GetStopStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*StopAndState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *GetStopStatesResponse) Reset() {
	*x = GetStopStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_v1_stop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStopStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStopStatesResponse) ProtoMessage() {}

func (x *GetStopStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_stop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStopStatesResponse.ProtoReflect.Descriptor instead.
func (*GetStopStatesResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_stop_proto_rawDescGZIP(), []int{4}
}

func (x *GetStopStatesResponse) GetStates() []*StopAndState {
	if x != nil {
		return x.States
	}
	return nil
}

var File_state_v1_stop_proto protoreflect.FileDescriptor

var file_state_v1_stop_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x22,
	0x4d, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x46,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x6f, 0x70, 0x41, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x2a, 0x4f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x47, 0x4f, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f,
	0x50, 0x10, 0x02, 0x42, 0x99, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x65,
	0x63, 0x6b, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x72, 0x61, 0x69, 0x6c, 0x32, 0x30,
	0x32, 0x33, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x53, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x08, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_state_v1_stop_proto_rawDescOnce sync.Once
	file_state_v1_stop_proto_rawDescData = file_state_v1_stop_proto_rawDesc
)

func file_state_v1_stop_proto_rawDescGZIP() []byte {
	file_state_v1_stop_proto_rawDescOnce.Do(func() {
		file_state_v1_stop_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_v1_stop_proto_rawDescData)
	})
	return file_state_v1_stop_proto_rawDescData
}

var file_state_v1_stop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_v1_stop_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_state_v1_stop_proto_goTypes = []interface{}{
	(StopStateEnum)(0),              // 0: state.v1.StopStateEnum
	(*StopAndState)(nil),            // 1: state.v1.StopAndState
	(*UpdateStopStateRequest)(nil),  // 2: state.v1.UpdateStopStateRequest
	(*UpdateStopStateResponse)(nil), // 3: state.v1.UpdateStopStateResponse
	(*GetStopStatesRequest)(nil),    // 4: state.v1.GetStopStatesRequest
	(*GetStopStatesResponse)(nil),   // 5: state.v1.GetStopStatesResponse
}
var file_state_v1_stop_proto_depIdxs = []int32{
	0, // 0: state.v1.StopAndState.state:type_name -> state.v1.StopStateEnum
	1, // 1: state.v1.UpdateStopStateRequest.state:type_name -> state.v1.StopAndState
	1, // 2: state.v1.GetStopStatesResponse.states:type_name -> state.v1.StopAndState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_state_v1_stop_proto_init() }
func file_state_v1_stop_proto_init() {
	if File_state_v1_stop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_state_v1_stop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAndState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_stop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStopStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_stop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStopStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_stop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStopStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_v1_stop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStopStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_v1_stop_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_v1_stop_proto_goTypes,
		DependencyIndexes: file_state_v1_stop_proto_depIdxs,
		EnumInfos:         file_state_v1_stop_proto_enumTypes,
		MessageInfos:      file_state_v1_stop_proto_msgTypes,
	}.Build()
	File_state_v1_stop_proto = out.File
	file_state_v1_stop_proto_rawDesc = nil
	file_state_v1_stop_proto_goTypes = nil
	file_state_v1_stop_proto_depIdxs = nil
}
