apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plarail

resources:
  - ../../base
  - namespace.yaml
  - ../../base/seed-data

configMapGenerator:
  - name: seed-data-config
    behavior: replace
    files:
      - seed-data.yaml
