apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plarail

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/ueckoken/plarail2023-dashboard
    newTag: main-bd20c2b-1750395692
