apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plarail

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/ueckoken/plarail2023-dashboard
    newTag: main-867dddd-1750441012
  - name: ghcr.io/ueckoken/plarail2023-autooperation:latest
    newTag: main-abd0b19-1750444269
