apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plarail

resources:
  - ../../base
  - namespace.yaml

images:
  - name: plarail2023/state-manager
    newName: plarail2023/state-manager
    newTag: local
  - name: plarail2023/auto-operation
    newName: plarail2023/auto-operation
    newTag: local
  - name: plarail2023/frontend
    newName: plarail2023/frontend
    newTag: local
  - name: plarail2023/proxy
    newName: plarail2023/proxy
    newTag: local

# ローカル開発用の設定
patchesStrategicMerge:
  - patches/storage-class.yaml
