apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plarail

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/ueckoken/plarail2023-dashboard
    newTag: main-522c9a9-1750476628
  - name: ghcr.io/ueckoken/plarail2023-autooperation:latest
    newTag: main-4d71821-1750477970
