apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: plarail2023
spec:
  interval: 10m
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
      enabled: true
      hosts:
        - "mqtt.plarail.k1h.dev"
      tls:
        - hosts:
            - "*.plarail.k1h.dev"
            - "plarail.k1h.dev"
          secretName: cloudflare-cert
    service:
      type: LoadBalancer
  chart:
    spec:
      chart: emqx
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 10m