apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: plarail2023
spec:
  interval: 10m
  values:
    service:
      type: LoadBalancer
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
      dashboard:
        enabled: true
        hosts:
          - emqx.plarail.k1h.dev
        path: /
        tls:
          - hosts:
              - emqx.plarail.k1h.dev
            secretName: cloudflare-cert
      wss:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "http"
          nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
          nginx.ingress.kubernetes.io/enable-real-ip: "true"
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
          nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/use-proxy-protocol: "false"
          nginx.ingress.kubernetes.io/proxy-protocol-header-timeout: "5s"
        path: /mqtt
        hosts:
          - wss.plarail.k1h.dev
        tls:
          - hosts:
              - wss.plarail.k1h.dev
            secretName: cloudflare-cert
  chart:
    spec:
      chart: emqx
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 10m