apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: plarail2023
spec:
  interval: 10m
  values:
    service:
      type: LoadBalancer
  chart:
    spec:
      chart: emqx
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 10m