apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-reflector
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: kubernetes-reflector
        namespace: flux-system
      interval: 1m