// @generated by protoc-gen-connect-query v0.6.0 with parameter "target=ts,import_extension=.ts"
// @generated from file state/v1/state.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlockStatesRequest, GetBlockStatesResponse, UpdateBlockStateRequest, UpdateBlockStateResponse } from "./block_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";
import { GetPointStatesRequest, GetPointStatesResponse, UpdatePointStateRequest, UpdatePointStateResponse } from "./point_pb.ts";
import { GetStopStatesRequest, GetStopStatesResponse, UpdateStopStateRequest, UpdateStopStateResponse } from "./stop_pb.ts";
import { AddTrainRequest, AddTrainResponse, GetTrainsRequest, GetTrainsResponse, UpdateTrainRequest, UpdateTrainResponse } from "./train_pb.ts";
import { createQueryService, createUnaryHooks, UnaryFunctionsWithHooks } from "@connectrpc/connect-query";

export const typeName = "state.v1.StateManagerService";

/**
 *
 * StateManagerが提供するサービス
 * AutoOperationとフロントエンド間の通信に利用される
 *
 * @generated from service state.v1.StateManagerService
 */
export const StateManagerService = {
  typeName: "state.v1.StateManagerService",
  methods: {
    /**
     * Block 
     *
     * @generated from rpc state.v1.StateManagerService.GetBlockStates
     */
    getBlockStates: {
      name: "GetBlockStates",
      I: GetBlockStatesRequest,
      O: GetBlockStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateBlockState
     */
    updateBlockState: {
      name: "UpdateBlockState",
      I: UpdateBlockStateRequest,
      O: UpdateBlockStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Point 
     *
     * @generated from rpc state.v1.StateManagerService.UpdatePointState
     */
    updatePointState: {
      name: "UpdatePointState",
      I: UpdatePointStateRequest,
      O: UpdatePointStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetPointStates
     */
    getPointStates: {
      name: "GetPointStates",
      I: GetPointStatesRequest,
      O: GetPointStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stop 
     *
     * @generated from rpc state.v1.StateManagerService.UpdateStopState
     */
    updateStopState: {
      name: "UpdateStopState",
      I: UpdateStopStateRequest,
      O: UpdateStopStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetStopStates
     */
    getStopStates: {
      name: "GetStopStates",
      I: GetStopStatesRequest,
      O: GetStopStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Train 
     *
     * @generated from rpc state.v1.StateManagerService.GetTrains
     */
    getTrains: {
      name: "GetTrains",
      I: GetTrainsRequest,
      O: GetTrainsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.AddTrain
     */
    addTrain: {
      name: "AddTrain",
      I: AddTrainRequest,
      O: AddTrainResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateTrain
     */
    updateTrain: {
      name: "UpdateTrain",
      I: UpdateTrainRequest,
      O: UpdateTrainResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

const $queryService = createQueryService({  service: StateManagerService,});

/**
 * Block 
 *
 * @generated from rpc state.v1.StateManagerService.GetBlockStates
 */
export const getBlockStates: UnaryFunctionsWithHooks<GetBlockStatesRequest, GetBlockStatesResponse> = {   ...$queryService.getBlockStates,  ...createUnaryHooks($queryService.getBlockStates)};

/**
 * @generated from rpc state.v1.StateManagerService.UpdateBlockState
 */
export const updateBlockState: UnaryFunctionsWithHooks<UpdateBlockStateRequest, UpdateBlockStateResponse> = {   ...$queryService.updateBlockState,  ...createUnaryHooks($queryService.updateBlockState)};

/**
 * Point 
 *
 * @generated from rpc state.v1.StateManagerService.UpdatePointState
 */
export const updatePointState: UnaryFunctionsWithHooks<UpdatePointStateRequest, UpdatePointStateResponse> = {   ...$queryService.updatePointState,  ...createUnaryHooks($queryService.updatePointState)};

/**
 * @generated from rpc state.v1.StateManagerService.GetPointStates
 */
export const getPointStates: UnaryFunctionsWithHooks<GetPointStatesRequest, GetPointStatesResponse> = {   ...$queryService.getPointStates,  ...createUnaryHooks($queryService.getPointStates)};

/**
 * Stop 
 *
 * @generated from rpc state.v1.StateManagerService.UpdateStopState
 */
export const updateStopState: UnaryFunctionsWithHooks<UpdateStopStateRequest, UpdateStopStateResponse> = {   ...$queryService.updateStopState,  ...createUnaryHooks($queryService.updateStopState)};

/**
 * @generated from rpc state.v1.StateManagerService.GetStopStates
 */
export const getStopStates: UnaryFunctionsWithHooks<GetStopStatesRequest, GetStopStatesResponse> = {   ...$queryService.getStopStates,  ...createUnaryHooks($queryService.getStopStates)};

/**
 * Train 
 *
 * @generated from rpc state.v1.StateManagerService.GetTrains
 */
export const getTrains: UnaryFunctionsWithHooks<GetTrainsRequest, GetTrainsResponse> = {   ...$queryService.getTrains,  ...createUnaryHooks($queryService.getTrains)};

/**
 * @generated from rpc state.v1.StateManagerService.AddTrain
 */
export const addTrain: UnaryFunctionsWithHooks<AddTrainRequest, AddTrainResponse> = {   ...$queryService.addTrain,  ...createUnaryHooks($queryService.addTrain)};

/**
 * @generated from rpc state.v1.StateManagerService.UpdateTrain
 */
export const updateTrain: UnaryFunctionsWithHooks<UpdateTrainRequest, UpdateTrainResponse> = {   ...$queryService.updateTrain,  ...createUnaryHooks($queryService.updateTrain)};
