//
//Train Proto
//駅に停車している列車の情報を扱うためのプロトコル

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: spec/train/v1/train.proto

package trainv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NfcUuid     string                 `protobuf:"bytes,1,opt,name=nfc_uuid,json=nfcUuid,proto3" json:"nfc_uuid,omitempty"`
	StationId   string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	ArrivalTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
}

func (x *Train) Reset() {
	*x = Train{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_train_v1_train_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_spec_train_v1_train_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_spec_train_v1_train_proto_rawDescGZIP(), []int{0}
}

func (x *Train) GetNfcUuid() string {
	if x != nil {
		return x.NfcUuid
	}
	return ""
}

func (x *Train) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *Train) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

type NotifyTrainArrivalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyTrainArrivalRequest) Reset() {
	*x = NotifyTrainArrivalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_train_v1_train_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTrainArrivalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTrainArrivalRequest) ProtoMessage() {}

func (x *NotifyTrainArrivalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_train_v1_train_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTrainArrivalRequest.ProtoReflect.Descriptor instead.
func (*NotifyTrainArrivalRequest) Descriptor() ([]byte, []int) {
	return file_spec_train_v1_train_proto_rawDescGZIP(), []int{1}
}

type NotifyTrainArrivalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *NotifyTrainArrivalResponse) Reset() {
	*x = NotifyTrainArrivalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_train_v1_train_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTrainArrivalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTrainArrivalResponse) ProtoMessage() {}

func (x *NotifyTrainArrivalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_train_v1_train_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTrainArrivalResponse.ProtoReflect.Descriptor instead.
func (*NotifyTrainArrivalResponse) Descriptor() ([]byte, []int) {
	return file_spec_train_v1_train_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyTrainArrivalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_spec_train_v1_train_proto protoreflect.FileDescriptor

var file_spec_train_v1_train_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x66, 0x63, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x66, 0x63, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x1a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x71,
	0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61,
	0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x72, 0x72,
	0x69, 0x76, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x9a, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x42, 0x0a, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x65, 0x63,
	0x6b, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x72, 0x61, 0x69, 0x6c, 0x32, 0x30, 0x32,
	0x33, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x08, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_train_v1_train_proto_rawDescOnce sync.Once
	file_spec_train_v1_train_proto_rawDescData = file_spec_train_v1_train_proto_rawDesc
)

func file_spec_train_v1_train_proto_rawDescGZIP() []byte {
	file_spec_train_v1_train_proto_rawDescOnce.Do(func() {
		file_spec_train_v1_train_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_train_v1_train_proto_rawDescData)
	})
	return file_spec_train_v1_train_proto_rawDescData
}

var file_spec_train_v1_train_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spec_train_v1_train_proto_goTypes = []interface{}{
	(*Train)(nil),                      // 0: train.v1.Train
	(*NotifyTrainArrivalRequest)(nil),  // 1: train.v1.NotifyTrainArrivalRequest
	(*NotifyTrainArrivalResponse)(nil), // 2: train.v1.NotifyTrainArrivalResponse
	(*timestamppb.Timestamp)(nil),      // 3: google.protobuf.Timestamp
}
var file_spec_train_v1_train_proto_depIdxs = []int32{
	3, // 0: train.v1.Train.arrival_time:type_name -> google.protobuf.Timestamp
	1, // 1: train.v1.TrainService.NotifyTrainArrival:input_type -> train.v1.NotifyTrainArrivalRequest
	2, // 2: train.v1.TrainService.NotifyTrainArrival:output_type -> train.v1.NotifyTrainArrivalResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_train_v1_train_proto_init() }
func file_spec_train_v1_train_proto_init() {
	if File_spec_train_v1_train_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_train_v1_train_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Train); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_train_v1_train_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyTrainArrivalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_train_v1_train_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyTrainArrivalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_train_v1_train_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_train_v1_train_proto_goTypes,
		DependencyIndexes: file_spec_train_v1_train_proto_depIdxs,
		MessageInfos:      file_spec_train_v1_train_proto_msgTypes,
	}.Build()
	File_spec_train_v1_train_proto = out.File
	file_spec_train_v1_train_proto_rawDesc = nil
	file_spec_train_v1_train_proto_goTypes = nil
	file_spec_train_v1_train_proto_depIdxs = nil
}
