apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: ghcr.io/ueckoken/plarail2023/proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3031
        env:
        - name: FRONTEND_URL
          value: "http://frontend"
        - name: BACKEND_URL
          value: "http://state-manager:8080"
