// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=dts+js"
// @generated from file state/v1/state.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlockStatesRequest, GetBlockStatesResponse, UpdateBlockStateRequest, UpdateBlockStateResponse } from "./block_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { GetPointStatesRequest, GetPointStatesResponse, UpdatePointStateRequest, UpdatePointStateResponse } from "./point_pb.js";
import { GetStopStatesRequest, GetStopStatesResponse, UpdateStopStateRequest, UpdateStopStateResponse } from "./stop_pb.js";
import { AddTrainRequest, AddTrainResponse, GetTrainsRequest, GetTrainsResponse, UpdateTrainRequest, UpdateTrainResponse } from "./train_pb.js";

/**
 *
 * StateManagerが提供するサービス
 * AutoOperationとフロントエンド間の通信に利用される
 *
 * @generated from service state.v1.StateManagerService
 */
export const StateManagerService = {
  typeName: "state.v1.StateManagerService",
  methods: {
    /**
     * Block 
     *
     * @generated from rpc state.v1.StateManagerService.GetBlockStates
     */
    getBlockStates: {
      name: "GetBlockStates",
      I: GetBlockStatesRequest,
      O: GetBlockStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateBlockState
     */
    updateBlockState: {
      name: "UpdateBlockState",
      I: UpdateBlockStateRequest,
      O: UpdateBlockStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Point 
     *
     * @generated from rpc state.v1.StateManagerService.UpdatePointState
     */
    updatePointState: {
      name: "UpdatePointState",
      I: UpdatePointStateRequest,
      O: UpdatePointStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetPointStates
     */
    getPointStates: {
      name: "GetPointStates",
      I: GetPointStatesRequest,
      O: GetPointStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stop 
     *
     * @generated from rpc state.v1.StateManagerService.UpdateStopState
     */
    updateStopState: {
      name: "UpdateStopState",
      I: UpdateStopStateRequest,
      O: UpdateStopStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.GetStopStates
     */
    getStopStates: {
      name: "GetStopStates",
      I: GetStopStatesRequest,
      O: GetStopStatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Train 
     *
     * @generated from rpc state.v1.StateManagerService.GetTrains
     */
    getTrains: {
      name: "GetTrains",
      I: GetTrainsRequest,
      O: GetTrainsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.AddTrain
     */
    addTrain: {
      name: "AddTrain",
      I: AddTrainRequest,
      O: AddTrainResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc state.v1.StateManagerService.UpdateTrain
     */
    updateTrain: {
      name: "UpdateTrain",
      I: UpdateTrainRequest,
      O: UpdateTrainResponse,
      kind: MethodKind.Unary,
    },
  }
};

