//
//Stop Proto
//ストップレールの状態を扱うプロトコル

// @generated by protoc-gen-es v1.4.2 with parameter "target=dts+js"
// @generated from file state/v1/stop.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum state.v1.StopStateEnum
 */
export declare enum StopStateEnum {
  /**
   * @generated from enum value: STOP_STATE_UNKNOWN = 0;
   */
  STOP_STATE_UNKNOWN = 0,

  /**
   * バーが下がってる状態
   *
   * @generated from enum value: STOP_STATE_GO = 1;
   */
  STOP_STATE_GO = 1,

  /**
   * バーが上がってる状態
   *
   * @generated from enum value: STOP_STATE_STOP = 2;
   */
  STOP_STATE_STOP = 2,
}

/**
 * @generated from message state.v1.StopAndState
 */
export declare class StopAndState extends Message<StopAndState> {
  /**
   * ポイントのid
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * ポイントの状態
   *
   * @generated from field: state.v1.StopStateEnum state = 2;
   */
  state: StopStateEnum;

  constructor(data?: PartialMessage<StopAndState>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.StopAndState";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopAndState;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopAndState;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopAndState;

  static equals(a: StopAndState | PlainMessage<StopAndState> | undefined, b: StopAndState | PlainMessage<StopAndState> | undefined): boolean;
}

/**
 *
 * UpdateStopState : ストップレールの状態を更新するAPI
 *
 * @generated from message state.v1.UpdateStopStateRequest
 */
export declare class UpdateStopStateRequest extends Message<UpdateStopStateRequest> {
  /**
   * @generated from field: state.v1.StopAndState state = 1;
   */
  state?: StopAndState;

  constructor(data?: PartialMessage<UpdateStopStateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.UpdateStopStateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateStopStateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateStopStateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateStopStateRequest;

  static equals(a: UpdateStopStateRequest | PlainMessage<UpdateStopStateRequest> | undefined, b: UpdateStopStateRequest | PlainMessage<UpdateStopStateRequest> | undefined): boolean;
}

/**
 * @generated from message state.v1.UpdateStopStateResponse
 */
export declare class UpdateStopStateResponse extends Message<UpdateStopStateResponse> {
  constructor(data?: PartialMessage<UpdateStopStateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.UpdateStopStateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateStopStateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateStopStateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateStopStateResponse;

  static equals(a: UpdateStopStateResponse | PlainMessage<UpdateStopStateResponse> | undefined, b: UpdateStopStateResponse | PlainMessage<UpdateStopStateResponse> | undefined): boolean;
}

/**
 *
 * GetStopStates : 全てのストップレールの状態を取得するAPI
 *
 * @generated from message state.v1.GetStopStatesRequest
 */
export declare class GetStopStatesRequest extends Message<GetStopStatesRequest> {
  constructor(data?: PartialMessage<GetStopStatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.GetStopStatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStopStatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStopStatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStopStatesRequest;

  static equals(a: GetStopStatesRequest | PlainMessage<GetStopStatesRequest> | undefined, b: GetStopStatesRequest | PlainMessage<GetStopStatesRequest> | undefined): boolean;
}

/**
 * @generated from message state.v1.GetStopStatesResponse
 */
export declare class GetStopStatesResponse extends Message<GetStopStatesResponse> {
  /**
   * @generated from field: repeated state.v1.StopAndState states = 1;
   */
  states: StopAndState[];

  constructor(data?: PartialMessage<GetStopStatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.GetStopStatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStopStatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStopStatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStopStatesResponse;

  static equals(a: GetStopStatesResponse | PlainMessage<GetStopStatesResponse> | undefined, b: GetStopStatesResponse | PlainMessage<GetStopStatesResponse> | undefined): boolean;
}

