//
//Train Proto
//駅に停車している列車の情報を扱うためのプロトコル

// @generated by protoc-gen-es v1.4.2 with parameter "target=dts+js"
// @generated from file state/v1/train.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum state.v1.Priority
 */
export declare enum Priority {
  /**
   * @generated from enum value: PRIORITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIORITY_LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: PRIORITY_HIGH = 2;
   */
  HIGH = 2,
}

/**
 * @generated from message state.v1.Train
 */
export declare class Train extends Message<Train> {
  /**
   * 列車ID(NFCのUUIDと一意に対応している)
   *
   * @generated from field: string train_id = 1;
   */
  trainId: string;

  /**
   * 駅 or 閉塞のID
   *
   * @generated from field: string position_id = 2;
   */
  positionId: string;

  /**
   * 列車の優先度
   *
   * @generated from field: state.v1.Priority priority = 3;
   */
  priority: Priority;

  constructor(data?: PartialMessage<Train>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.Train";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Train;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Train;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Train;

  static equals(a: Train | PlainMessage<Train> | undefined, b: Train | PlainMessage<Train> | undefined): boolean;
}

/**
 *
 * GetTrains : 列車の状態を取得するAPI
 *
 * @generated from message state.v1.GetTrainsRequest
 */
export declare class GetTrainsRequest extends Message<GetTrainsRequest> {
  constructor(data?: PartialMessage<GetTrainsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.GetTrainsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrainsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrainsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrainsRequest;

  static equals(a: GetTrainsRequest | PlainMessage<GetTrainsRequest> | undefined, b: GetTrainsRequest | PlainMessage<GetTrainsRequest> | undefined): boolean;
}

/**
 * @generated from message state.v1.GetTrainsResponse
 */
export declare class GetTrainsResponse extends Message<GetTrainsResponse> {
  /**
   * @generated from field: repeated state.v1.Train trains = 1;
   */
  trains: Train[];

  constructor(data?: PartialMessage<GetTrainsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.GetTrainsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrainsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrainsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrainsResponse;

  static equals(a: GetTrainsResponse | PlainMessage<GetTrainsResponse> | undefined, b: GetTrainsResponse | PlainMessage<GetTrainsResponse> | undefined): boolean;
}

/**
 *
 * UpdateTrainUUID : NFCのUUID紐付けを更新するAPI
 *
 * @generated from message state.v1.UpdateTrainUUIDRequest
 */
export declare class UpdateTrainUUIDRequest extends Message<UpdateTrainUUIDRequest> {
  /**
   * 列車ID
   *
   * @generated from field: string train_id = 1;
   */
  trainId: string;

  /**
   * NFCのUUID
   *
   * @generated from field: string uuid = 2;
   */
  uuid: string;

  constructor(data?: PartialMessage<UpdateTrainUUIDRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.UpdateTrainUUIDRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateTrainUUIDRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateTrainUUIDRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateTrainUUIDRequest;

  static equals(a: UpdateTrainUUIDRequest | PlainMessage<UpdateTrainUUIDRequest> | undefined, b: UpdateTrainUUIDRequest | PlainMessage<UpdateTrainUUIDRequest> | undefined): boolean;
}

/**
 * @generated from message state.v1.UpdateTrainUUIDResponse
 */
export declare class UpdateTrainUUIDResponse extends Message<UpdateTrainUUIDResponse> {
  constructor(data?: PartialMessage<UpdateTrainUUIDResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "state.v1.UpdateTrainUUIDResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateTrainUUIDResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateTrainUUIDResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateTrainUUIDResponse;

  static equals(a: UpdateTrainUUIDResponse | PlainMessage<UpdateTrainUUIDResponse> | undefined, b: UpdateTrainUUIDResponse | PlainMessage<UpdateTrainUUIDResponse> | undefined): boolean;
}

