//
//Train Proto
//駅に停車している列車の情報を扱うためのプロトコル

// @generated by protoc-gen-es v1.4.2 with parameter "target=dts+js"
// @generated from file state/v1/train.proto (package state.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum state.v1.Priority
 */
export const Priority = proto3.makeEnum(
  "state.v1.Priority",
  [
    {no: 0, name: "PRIORITY_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "PRIORITY_LOW", localName: "LOW"},
    {no: 2, name: "PRIORITY_HIGH", localName: "HIGH"},
  ],
);

/**
 * @generated from message state.v1.Train
 */
export const Train = proto3.makeMessageType(
  "state.v1.Train",
  () => [
    { no: 1, name: "train_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "station_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 *
 * GetTrains : 列車の状態を取得するAPI
 *
 * @generated from message state.v1.GetTrainsRequest
 */
export const GetTrainsRequest = proto3.makeMessageType(
  "state.v1.GetTrainsRequest",
  [],
);

/**
 * @generated from message state.v1.GetTrainsResponse
 */
export const GetTrainsResponse = proto3.makeMessageType(
  "state.v1.GetTrainsResponse",
  () => [
    { no: 1, name: "trains", kind: "message", T: Train, repeated: true },
  ],
);

/**
 *
 * UpdateTrainUUID : NFCのUUID紐付けを更新するAPI
 *
 * @generated from message state.v1.UpdateTrainUUIDRequest
 */
export const UpdateTrainUUIDRequest = proto3.makeMessageType(
  "state.v1.UpdateTrainUUIDRequest",
  () => [
    { no: 1, name: "train_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message state.v1.UpdateTrainUUIDResponse
 */
export const UpdateTrainUUIDResponse = proto3.makeMessageType(
  "state.v1.UpdateTrainUUIDResponse",
  [],
);

