name: compile_PB

on:
  push:
    branches-ignore:
      - "main"
      - "deployment"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      # - name: Set up Node in ats
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: add path
        run: |-
          echo "$RUNNER_TEMP/protoc/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: bufbuild/install
        uses: bufbuild/buf-setup-action@v1.27.2
        with:
          version: v1.27.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup protoc
        uses: arduino/setup-protoc@v2
      - name: prepare protoc
        run: |-
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          mkdir -p $GITHUB_WORKSPACE/backend/spec
      - name: gen proto
        run: |-
          buf generate
        working-directory: proto
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          # FIXME: 自動生成結果にテストを実行するためにPATかgithub appsのtokenを使う