# https://songmu.jp/riji/entry/2022-08-05-git-pr-release.html
name: Create Release PR
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: gem install --no-document git-pr-release
      - run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: deployment
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: pr-release
          TZ: Asia/Tokyo
