name: ESP32 Cam UDP CI

on:
  push:
    branches:
      - "main"
      - "deployment"
    paths:
      - "hardware/esp32-cam-udp/**"
  pull_request:
    paths:
      - "hardware/esp32-cam-udp/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hardware/esp32-cam-udp

    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install 1
    - name: Run PlatformIO
      run: pio run