name: Lint and Test golang

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  # golangci:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.21'
  #         cache: false
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.54
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build State manager
        run: |
          go build -race backend/state-manager/cmd/main.go
      - name: Test
        run: |
          go test -v ./...
